### PR TITLE
Terminate OPTIONS request without sending it to the backend.

### LINKED ISSUE #6: Feature Request: Terminating preflight options requests
When it comes to preflight OPTIONS requests, the only thing the browser really cares about is the access control headers. If we're making HAProxy responsible for handling all of these headers, it makes sense that it could also terminate the request, without needing to forward it through to an underlying api server.

This is something I know is possible with NGINX but I'm having a hard time finding information about how to do it with HAProxy. It would be nice if this library had some way of handling it, though barring that, some assistance in scripting it myself-- or even insight into whether or not this kind of thing is even possible with HAProxy-- would be super helpful.

Thanks ahead of time.

### PR DESCRIPTION
**Pull request by aleskiontherun**
Fixes #6

### CODE REVIEW

**Comment by NickMRamirez** [comment]
Thanks for the pull request @dizeee. Unfortunately, in its current state, this does not work because it doesn't send back the `Access-Control-Allow-Methods` response header for an OPTIONS request.

**Comment by aleskiontherun** [comment]
@NickMRamirez I tested with HAProxy 2.1.4, and it does. `Access-Control-Allow-Methods` header is added by `preflight_request` function, which is executed before returning the response.

Billie_Account_UI

**Comment by erolg** [comment]
@dizeee 

It works but I got the following alert:

```
haproxy[1414]: [ALERT] 226/212022 (7638) : Lua applet http '<lua.empty-response>': runtime error: /var/lib/haproxy/cors.lua:91: bad argument #1 to 'send' (string expected, got nil) from [C] method 'send', /var/lib/haproxy/cors.lua:91 C function line 87.
```

Alert gone when I changed send function like that: `applet:send("")`

**Comment by NickMRamirez** [comment]
I've updated the module to terminate preflight requests using the new Reply object in the HAProxy Lua library, but it does require HAProxy 2.2. https://github.com/haproxytech/haproxy-lua-cors/pull/15

**Pull request closed without merging**
