### PR TITLE
Additional Origin from HAProxy configuration

### PR DESCRIPTION
**Pull request by wwwlde**
Hello!

We need to add to the list of allowed origins some hostnames from custom headers, so here are a few rows of code to do this. Maybe it would be helpful to somebody, or please suggest some other way to do the same without modification of the script.

Thanks in advance! Thanks for your job!

### CODE REVIEW

**Comment by NickMRamirez** [comment]
Would this not open a way for malicious users to send the HTTP request header themselves to modify the allowed origins list?

**Comment by wwwlde** [comment]
> Would this not open a way for malicious users to send the HTTP request header themselves to modify the allowed origins list?

No, in any way. In any case, common sense is needed.

Our custom header is calculated from a safe source in our Haproxy configuration.

This code was a result of the fact that we did not find a way to push our variable as a parameter into the script.

**Comment by NickMRamirez** [comment]
I understand now that you want to create an HTTP API for adding allowed origins, and the interface for it would be HTTP request headers. I'm not convinced that this is a safe thing to do as it would open the possibility of an attacker learning the name of the header and passing in their own allowed origin.

Yet, the idea of making the origin list dynamic -- using a variable -- seems worthwhile.

The approach of setting a variable named `custom_allowed_origins` would, in my opinion, make this CORS library's interface slightly more complicated because it would add a new `http-request set-var` feature, which the code then needs to look for that exact variable name. I'd like to find a way to extend the existing function (`http-request lua.cors`) to accept variables instead. That way, we're not adding a new interface to the CORS library.

I think it can be done. Possibly, the Lua code could check if the argument passed in begins with a variable prefix `txn.` and if so, assume the value is a variable and then get that variable from HAProxy using the Lua function [TXN.get_var](https://www.arpalert.org/src/haproxy-lua-api/2.6/index.html#TXN.get_var). Something like:

```
http-request lua.cors "*" "txn.myorigins" "*"
```

That is, unless `var(txn.myorigins)` works out of the box. I haven't tried it yet.

```
http-request lua.cors "*" var(txn.myorigins) "*"
```

What do you think?

**Comment by wwwlde** [comment]
It appears to be appealing!

The last option(with var() as parameter), did not work for us because the variable was not initialized and was passed as text.

In general, the implementation I provided is not suitable for you, but it works perfectly in our case. I will try to find the time to redo code, despite of I am not very good at LUA.

Thank you for your time and proposals. I'll return with a new version.

Thanks!

**Pull request closed without merging**
